@DevFreela.API_HostAddress = https://localhost:44344

GET {{DevFreela.API_HostAddress}}/weatherforecast/
Accept: application/json

###

@query=abc
GET {{DevFreela.API_HostAddress}}/api/projects?query={{query}}

###
